### ISSUE TITLE
Agregar metodos para ABM

### ISSUE THREAD

**Issue by felipevanc** [felipevanc/SB-FACTORY#3]
Fran, quedo muy util y simple esta herramienta. Ahora habria que agregar tres metodos, abajo de las propiedades:

1) Function Crear, recibe todos los campos, devuelve Id del nuevo registro creado.
El sp se debe llamar: usp_<<nombre clase>>_Crear

2) Sub Eliminar, recibe el Id
El sp se debe llamar: usp_<<nombre clase>>_Eliminar

2) Sub Actualizar, recibe el Id y luego todos los campos
El sp se debe llamar: usp_<<nombre clase>>_Actualizar

**Comment by githubmg** [comment]
Hola Felipe

  Te subí los nuevos métodos a una branch nueva.

   Los métodos los hice SHARED porque como me dijiste que reciben parámetros imaginé que no usaba las propiedades del objeto.  Si hay que cambiarlo, me avisás y lo modifico.

Saludos

**Comment by felipevanc** [comment]
Perfecto, lo cierro
